/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NGL__factory } from './NGL__factory';
export { StakingBuilding__factory } from './StakingBuilding__factory';
