/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as factories from './factories';
export { NGL__factory } from './factories/NGL__factory';
export { StakingBuilding__factory } from './factories/StakingBuilding__factory';
export type { NGL } from './NGL';
export type { StakingBuilding } from './StakingBuilding';
